# Generated by Django 5.2.5 on 2025-12-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=20),
        ),
    ]
